fix(model-datastructure): make `MapBasedStore` thread safe
Make it thread safe by using a synchronized map.

Missing thread safety is the suspected issue for such error messages

```
2024-03-20 08:58:01,282 [  48184]  ERROR - #com.intellij.ide.plugins.PluginManager - Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class java.lang.String id= 996201210 hashCode= -209607169 toString= sHB6r*02gLuXVEvI31E7v9ijDVL5VSdSO8F9OO-2z2CA; object #2 =class java.lang.String id= 1530156665 hashCode= -209607169 toString= sHB6r*02gLuXVEvI31E7v9ijDVL5VSdSO8F9OO-2z2CA
[Warning] apparent concurrent modification of the key set. Size before and after rehash() do not match 81 vs 83
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class java.lang.String id= 996201210 hashCode= -209607169 toString= sHB6r*02gLuXVEvI31E7v9ijDVL5VSdSO8F9OO-2z2CA; object #2 =class java.lang.String id= 1530156665 hashCode= -209607169 toString= sHB6r*02gLuXVEvI31E7v9ijDVL5VSdSO8F9OO-2z2CA
[Warning] apparent concurrent modification of the key set. Size before and after rehash() do not match 81 vs 83
	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.map.hash.THashMap.rehash(THashMap.java:403)
	at gnu.trove.impl.hash.THash.ensureCapacity(THash.java:175)
	at gnu.trove.map.hash.THashMap.putAll(THashMap.java:551)
	at org.modelix.model.persistent.MapBasedStore.putAll(MapBasedStore.kt:54)
```